<?php
/**
 * @file
 * Code for the ag_section_podcast feature.
 */

include_once 'ag_section_podcast.features.inc';
include_once drupal_get_path('module', 'ag_section_podcast') . '/includes/ag_section_podcast.forms.inc';

/////////////
/// HOOKS ///
/////////////

/**
 * Implements hook_preprocess_node().
 */
function ag_section_podcast_preprocess_node(&$vars) {
  if ($vars['type'] == 'podcast' && $vars['view_mode'] == 'full') {
    drupal_add_css(drupal_get_path('module', 'ag_section_podcast') . '/css/sc-player-standard.css');
    drupal_add_js(drupal_get_path('module', 'ag_section_podcast') . '/js/soundcloud.player.api.js');
    drupal_add_js(drupal_get_path('module', 'ag_section_podcast') . '/js/sc-player.js');
  }
}

/**
 * Implements hook_preprocess_field().
 */
function ag_section_podcast_preprocess_field(&$vars) {
  if ($vars['element']['#field_name'] == 'field_podcast_url') {
    // Check if resource exists in Soundcloud.
    // Soundcloud app connection.
    $soundcloud = soundcloud_app_connection();
    $soundcloud
      ->get('/resolve')
      ->setParams(array('url' => $vars['element']['#items'][0]['url']));
    $response = $soundcloud->request()->bodyArray();

    if ($response['status'] == '302 - Found') {
      $vars['items'][0]['#markup'] = l('', $vars['element']['#items'][0]['url'],
        array(
          'attributes' => array(
            'class' => 'sc-player'
          )
        )
      );
    }
    else {
      $vars['items'][0] = array(
        '#prefix' => '<span class="not-found">',
        '#markup' => t('Requested request is not available. Please contact the site administrator.'),
        '#suffix' => '</span>'
      );
    }
  }
}
