<?php
/**
 * @file
 * ag_section_search_solr_sarnia.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function ag_section_search_solr_sarnia_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['ag_section_search_solr_sarnia-facet-addressee-home'] = array(
    'cache' => 1,
    'css_class' => 'ag-block-sm-home',
    'custom' => 0,
    'delta' => 'facet-addressee-home',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'ag_section_search_solr_sarnia',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Destinatario',
    'visibility' => 0,
  );

  $export['ag_section_search_solr_sarnia-facet-educational-level-home'] = array(
    'cache' => 1,
    'css_class' => 'ag-block-sm-home',
    'custom' => 0,
    'delta' => 'facet-educational-level-home',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'ag_section_search_solr_sarnia',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Nivel educativo',
    'visibility' => 0,
  );

  $export['ag_section_search_solr_sarnia-facet-resource-type-home'] = array(
    'cache' => 1,
    'css_class' => 'ag-block-sm-home',
    'custom' => 0,
    'delta' => 'facet-resource-type-home',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'ag_section_search_solr_sarnia',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Tipo de recurso',
    'visibility' => 0,
  );

  $export['facetapi-1g7QrM1nLxJnz4yu0S3m5kRbsSwpzJPl'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '1g7QrM1nLxJnz4yu0S3m5kRbsSwpzJPl',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Licencia',
    'visibility' => 0,
  );

  $export['facetapi-67Vva9K890W6XnBroP00cMS1HkYumWKg'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '67Vva9K890W6XnBroP00cMS1HkYumWKg',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Asignatura',
    'visibility' => 0,
  );

  $export['facetapi-DGDQna1S4A9h3rNYIObowFA4HwnaY4SZ'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'DGDQna1S4A9h3rNYIObowFA4HwnaY4SZ',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Destinatario',
    'visibility' => 0,
  );

  $export['facetapi-FvHSaxLFZvXoPiehvph8YzJAYoy5JlT1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'FvHSaxLFZvXoPiehvph8YzJAYoy5JlT1',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Nivel educativo',
    'visibility' => 0,
  );

  $export['facetapi-K1PTN04nyUa80OO00NSjBYp1DRV141Fw'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'K1PTN04nyUa80OO00NSjBYp1DRV141Fw',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Etiquetas',
    'visibility' => 0,
  );

  $export['facetapi-KC5Ga0OR3qIiM7XvpFJwXcTNkhpV044K'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'KC5Ga0OR3qIiM7XvpFJwXcTNkhpV044K',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Administradores',
    'visibility' => 0,
  );

  $export['facetapi-N1LfGkWHLTUSjH21hcDcSvMgCq8gg0eZ'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'N1LfGkWHLTUSjH21hcDcSvMgCq8gg0eZ',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Etiquetas',
    'visibility' => 0,
  );

  $export['facetapi-ROZC2fsGftBFe7CUp53fpU14EWC04kY0'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ROZC2fsGftBFe7CUp53fpU14EWC04kY0',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Etiquetas',
    'visibility' => 0,
  );

  $export['facetapi-S2110LVPO8EFLuD3miE1qyyeaYbDjKAo'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'S2110LVPO8EFLuD3miE1qyyeaYbDjKAo',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Proceso cognitivo',
    'visibility' => 0,
  );

  $export['facetapi-VQ4Dk1zUG0heSr62N8qcLeLQUknmdhSw'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'VQ4Dk1zUG0heSr62N8qcLeLQUknmdhSw',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Etiquetas',
    'visibility' => 0,
  );

  $export['facetapi-XfaCoysJPGvzy3TEue0eG5m8LizDMw5V'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'XfaCoysJPGvzy3TEue0eG5m8LizDMw5V',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Tipo',
    'visibility' => 0,
  );

  $export['facetapi-fZ8hwdrUlnRle1W1cgtUDpfhQb0lMJny'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'fZ8hwdrUlnRle1W1cgtUDpfhQb0lMJny',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'País',
    'visibility' => 0,
  );

  $export['facetapi-hN0cvmOdSxIblf7EZA6EpTuhm72kZnBx'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'hN0cvmOdSxIblf7EZA6EpTuhm72kZnBx',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Etiquetas',
    'visibility' => 0,
  );

  $export['facetapi-lcnsQqBL6qV0ugkbiTnpHoCR01RCivpB'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'lcnsQqBL6qV0ugkbiTnpHoCR01RCivpB',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Palabra clave',
    'visibility' => 0,
  );

  $export['facetapi-ma1d52CwfDzxinOtMpP0fh3VnAv7A2oD'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ma1d52CwfDzxinOtMpP0fh3VnAv7A2oD',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Localidad',
    'visibility' => 0,
  );

  $export['facetapi-roc1KSTOx3C0YknUzGiotyrJVjxEGcFR'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'roc1KSTOx3C0YknUzGiotyrJVjxEGcFR',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Tipo de recurso',
    'visibility' => 0,
  );

  $export['facetapi-xYqfASAcKM6IlyM452hhqmSalTUbqCeU'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'xYqfASAcKM6IlyM452hhqmSalTUbqCeU',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Provincia',
    'visibility' => 0,
  );

  return $export;
}
