# A sample Gemfile
source "https://rubygems.org"

gem 'sass'                    # Sass.
gem 'compass'                 # Framework built on Sass.
gem 'compass-validator'       # So you can `compass validate`.
gem 'oily_png'                # Faster Compass sprite generation.
gem 'css_parser'              # Helps `compass stats` output statistics.
gem 'guard'                   # Guard event handler.
gem 'guard-compass'           # Compile on sass/scss change.
gem 'guard-shell'             # Run shell commands.
gem 'guard-livereload', '~> 2.3.0' # Browser reload.
gem 'rb-inotify'
gem 'breakpoint'
gem 'compass-sourcemaps', "~> 0.12.4.sourcemaps.a4836f1"
