<?php
/**
 * @file
 * Code for the ag_section_webinar feature.
 */

include_once 'ag_section_webinar.features.inc';
include_once drupal_get_path('module', 'ag_section_webinar') . '/includes/ag_section_webinar.forms.inc';

/////////////
/// HOOKS ///
/////////////

/**
 * Implements hook_menu().
 */
function ag_section_webinar_menu() {
  $items = array();

  $items['ag_section_webinar/%/%/%user'] = array(
    'title' => 'Ag webinar subscribe-unsubscribe',
    'page callback' => 'ag_section_webinar_manage_webinar_subscriptions',
    'page arguments' => array(1, 2, 3),
    'access callback' => TRUE,
    'file' => 'includes/ag_section_webinar.forms.inc',
  );

  return $items;
}

/**
 * Implements hook_node_view().
 */
function ag_section_webinar_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'webinar' && $view_mode == 'full') {
    global $user;

    // Hide webinar register link if current date is over webinar date or the
    // user has already registered.
    $current_time = time();
    $webinar_date = webinar_date_timestamp($node);

    // Class duration in seconds.
    $duration = $node->field_duracion[LANGUAGE_NONE][0]['value'] * 60;

    // Recording class.
    $recording = $node->field_record_webinar[LANGUAGE_NONE][0]['value'] == 0 ? FALSE : TRUE;

    // Show subscription/login button.
    if ($current_time < $webinar_date + $duration) {
      $query = db_select('webinar_attendees', 'wa');
      $query->fields('wa',array('webinar_url'));
      $query->condition('wa.uid', $user->uid, '=');
      $query->condition('wa.classid', $node->field_classid[LANGUAGE_NONE][0]['value'], '=');

      $result = $query->execute();
      $webinar_url = $result->fetchCol();

      $class_id = $node->field_classid[LANGUAGE_NONE][0]['value'];
      $subscribe_link = ag_section_webinar_retrieve_subscribe_user_link($class_id, $webinar_url, $user);
      if (!empty($subscribe_link)) {
        $node->content['webinar_subscription'] = $subscribe_link;
      }
    }

    // Hide webinar record link if webinar has not yet been held or not
    // recording selected.
    if ($current_time < $webinar_date + $duration + 300 || !$recording) {
      $node->content['field_recording_url']['#access'] = FALSE;
    }
  }
}
