<?php
/**
 * @file
 * ag_home.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function ag_home_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['bean-banner-home---articulos'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'banner-home---articulos',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-banner-home---comunidades'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'banner-home---comunidades',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-banner-home---encuentra-personas'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'banner-home---encuentra-personas',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-banner-home---eventos'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'banner-home---eventos',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-banner-home---localiza-contenido'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'banner-home---localiza-contenido',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-banner-home---mantente-actualiza'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'banner-home---mantente-actualiza',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-banner-home---recursos'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'banner-home---recursos',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['bean-banner-home---vistazo'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'banner-home---vistazo',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'bean',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'nexus' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nexus',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
